app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('admin', function () {
    return view('admin.admin_template');
});
Route::get('test', 'TestController@index');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
	Route::resource('users', 'UsersController');
	Route::get('users/{id}/destroy', [
		'uses' => 'UsersController@destroy',
		'as' => 'admin.users.destroy'
		]);
	Route::resource('categories', 'CategoriesController');
	Route::get('categories/{id}/destroy',[
		'uses' => 'CategoriesController@destroy',
		'as' => 'admin.categories.destroy'
		]);
	Route::resource('tags','TagsController');
	Route::get('tags/{id}/destroy',[
		'uses' => 'TagsController@destroy',
		'as' => 'admin.tags.destroy'
		]);
	Route::resource('articles', 'ArticlesController');
	Route::get('articles/{id}/destroy',[
		'uses' => 'ArticlesController@destroy',
		'as' => 'admin.articles.destroy'
		]);
	Route::get('image',[
		'uses' => 'ImageController@index',
		'as' => 'admin.image.index'
		]);
});
Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
	]);
Route::post('auth/login',[
	'uses' =>  'Auth\AuthController@postLogin',
	'as' => 'auth.login'
	]);
Route::get('auth/logout', [
	'uses' => 'Auth\AuthController@getLogout',
	'as' => 'auth.logout'
	]);

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = "tags";
    protected $fillable = ['name'];

    public function articles(){
    	return $this->belongsToMany('App\Article');
    }

    public function scopeSearch($query, $name){
    	return $query->where('name','LIKE',"%$name%");
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\TagRequest;
use App\Http\Controllers\Controller;
use App\Tag;
use Laracasts\Flash\Flash;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tags = Tag::search($request->name)->orderBy('id','DESC')->paginate(5);   
        return view('tags.index')->with('tags',$tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        $tag = new Tag($request->all());
        $tag->save();

        Flash::success('El tag' .$tag->name. ' ha sido creada correctamente');
        return redirect()->route('admin.tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags = Tag::find($id);
        return view('tags.edit')->with('tags',$tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $tag->fill($request->all());
        $tag->save();

        Flash::success('El tag '.$tag->name. ' fue modificado correctamente!');
        return redirect()->route('admin.tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->delete();
        Flash::error('El tag '.$tag->name. ' ha sido eliminado');
        return redirect()->route('admin.tags.index');
    }
}

resources/views/tags/create.blade.php
@extends('admin.admin_template')
@section('title', 'Crear Tag')
@section('content')
	{!! Form::open(['route' => 'admin.tags.store', 'method' => 'POST']) !!}
		<div class="form-group">
			{!! Form::label('name', 'Nombre') !!}
			{!! Form::text('name',null,['class' => 'form-control', 'placeholder' => 'Nombre', 'required']) !!}	
		</div>
		<div class="form-group">
			{!! Form::submit('Registrar',['class' => 'btn btn-primary']) !!}
		</div>
	{!! Form::close() !!}
@endsection

resources/views/tags/edit.blade.php
@extends('admin.admin_template')
@section('title', 'Editar Tag')
@section('content')
	{!! Form::open(['route' => ['admin.tags.update',$tags], 'method' => 'PUT']) !!}
		<div class="form-group">
			{!! Form::label('name', 'Nombre') !!}
			{!! Form::text('name',$tags->name,['class' => 'form-control', 'placeholder' => 'Nombre', 'required']) !!}	
		</div>
		<div class="form-group">
			{!! Form::submit('Registrar',['class' => 'btn btn-primary']) !!}
		</div>
	{!! Form::close() !!}
@endsection

resources/views/tags/index.blade.php
@extends('admin.admin_template')
@section('title','Listado de Tags')
@section('content')
	<a href="{{ route('admin.tags.create') }}" class="btn btn-info">Registrar nuevo Tag</a>
	<!--Buscador de Tags -->
		{!! Form::open(['route' => 'admin.tags.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
			<div class="input-group">
				{!! Form::text('name', null,['class' => 'form-control', 'placeholder' => 'Buscar Tag', 'aria-describedby' => 'search']) !!}
				<span class="input-group-addon" id="search"><span class="glyphicon glyphicon-search"></span></span>
			</div>
		{!! Form::close() !!}
	<!-- Fin buscador -->
	<table class="table table-striped">
		<thead>
			<th>ID</th>
			<th>Nombre</th>
			<th>Action</th>
		</thead>
		<tdoby>
			@foreach($tags as $tag)
			<tr>
				<td>{{ $tag->id }}</td>
				<td>{{ $tag->name }}</td>
				<td>
					<a href="{{ route('admin.tags.edit', $tag->id) }}" class="btn btn-warning glyphicon glyphicon-wrench" style="width: 15%; margin:3px "></a>
					<a href="{{ route('admin.tags.destroy', $tag->id) }}" onclick="return confirm('¿Estas seguro de eliminar esta categoria?')" class="btn btn-danger glyphicon glyphicon-remove-circle" style="width: 15%; margin: 3px"></a>
				</td>
			</tr>
			@endforeach
		</tdoby>
	</table>
	<div class="text-center">
		{!! $tags->render() !!}
	</div>
@endsection