app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('admin', function () {
    return view('admin.admin_template');
});
Route::get('test', 'TestController@index');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
	Route::resource('users', 'UsersController');
	Route::get('users/{id}/destroy', [
		'uses' => 'UsersController@destroy',
		'as' => 'admin.users.destroy'
		]);
	Route::resource('categories', 'CategoriesController');
	Route::get('categories/{id}/destroy',[
		'uses' => 'CategoriesController@destroy',
		'as' => 'admin.categories.destroy'
		]);
	Route::resource('tags','TagsController');
	Route::get('tags/{id}/destroy',[
		'uses' => 'TagsController@destroy',
		'as' => 'admin.tags.destroy'
		]);
	Route::resource('articles', 'ArticlesController');
	Route::get('articles/{id}/destroy',[
		'uses' => 'ArticlesController@destroy',
		'as' => 'admin.articles.destroy'
		]);
	Route::get('image',[
		'uses' => 'ImageController@index',
		'as' => 'admin.image.index'
		]);
});
Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
	]);
Route::post('auth/login',[
	'uses' =>  'Auth\AuthController@postLogin',
	'as' => 'auth.login'
	]);
Route::get('auth/logout', [
	'uses' => 'Auth\AuthController@getLogout',
	'as' => 'auth.logout'
	]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";
    protected $fillable = ['name'];

    public function articles(){
    	return $this->hasMany('App\Article');
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Category;
use Laracasts\Flash\Flash;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id','DESC')->paginate(3);
        return view('categories.index')->with('categories',$categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $categories = new Category($request->all());
        $categories->save();

        Flash::success('La categoria' . $categories->name . " fue creada con exito!");
        return redirect()->route('admin.categories.index');
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::find($id);
        return view('categories.edit')->with('categories',$categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categories = Category::find($id);
        $categories->fill($request->all());
        $categories->save();

        Flash::success('Categoria ' . $categories->name . " editado correctamente");
        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categories = Category::find($id);
        $categories->delete();

        Flash::error('La categoria '. $categories->name . " fue eliminada");
        return redirect()->route('admin.categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('admin.admin_template')

@section('title', 'Crear Categoria')
@section('content')

	{!! Form::open(['route' => 'admin.categories.store', 'method' => 'POST']) !!}
		<div class="form-group">
			{!! Form::label('name', 'Nombre:') !!}
			{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' =>'Categories', 'required']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('Registrar', ['class' => 'btn btn-primary']) !!}
		</div>
	{!! Form::close() !!}
@endsection

resources/views/categories/edit.blade.php
@extends('admin.admin_template')

@section('title', 'Modificar Categoria')
@section('content')

	{!! Form::open(['route' => ['admin.categories.update', $categories->id], 'method' => 'PUT']) !!}
		<div class="form-group">
			{!! Form::label('name', 'Nombre: ') !!}
			{!! Form::text('name',$categories->name,['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('Editar',['class' => 'btn btn-primary']) !!}
		</div>
	{!! Form::close() !!}

@endsection

resources/views/categories/index.blade.php
@extends('admin.admin_template')

@section('title', 'Listado de Categorias')
@section('content')
	<a href="{{ route('admin.categories.create') }}" class="btn btn-info">Registrar nueva categoria</a>
	<table class="table table-striped">
		<thead>
			<th>ID</th>
			<th>Name</th>
			<th>Action</th>
		</thead>
		@foreach($categories as $category)
		<tbody>
			<td>{{ $category->id }}</td>
			<td>{{ $category->name }}</td>
			<td>
				<a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-warning glyphicon glyphicon-wrench" style="width: 15%; margin:3px "></a>
				<a href="{{ route('admin.categories.destroy', $category->id) }}" onclick="return confirm('¿Estas seguro de eliminar esta categoria?')" class="btn btn-danger glyphicon glyphicon-remove-circle" style="width: 15%; margin: 3px"></a>
			</td>
		</tbody>
		@endforeach
	</table>
	{!! $categories->render() !!}
@endsection