app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('admin', function () {
    return view('admin.admin_template');
});
Route::get('test', 'TestController@index');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
	Route::resource('users', 'UsersController');
	Route::get('users/{id}/destroy', [
		'uses' => 'UsersController@destroy',
		'as' => 'admin.users.destroy'
		]);
	Route::resource('categories', 'CategoriesController');
	Route::get('categories/{id}/destroy',[
		'uses' => 'CategoriesController@destroy',
		'as' => 'admin.categories.destroy'
		]);
	Route::resource('tags','TagsController');
	Route::get('tags/{id}/destroy',[
		'uses' => 'TagsController@destroy',
		'as' => 'admin.tags.destroy'
		]);
	Route::resource('articles', 'ArticlesController');
	Route::get('articles/{id}/destroy',[
		'uses' => 'ArticlesController@destroy',
		'as' => 'admin.articles.destroy'
		]);
	Route::get('image',[
		'uses' => 'ImageController@index',
		'as' => 'admin.image.index'
		]);
});
Route::get('auth/login', [
	'uses' => 'Auth\AuthController@getLogin',
	'as' => 'auth.login'
	]);
Route::post('auth/login',[
	'uses' =>  'Auth\AuthController@postLogin',
	'as' => 'auth.login'
	]);
Route::get('auth/logout', [
	'uses' => 'Auth\AuthController@getLogout',
	'as' => 'auth.logout'
	]);

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;


class Article extends Model implements SluggableInterface
{ 
	use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'title',
        'save_to'    => 'slug',
    ];

    protected $table = "articles";
    protected $fillable = ['title',
    						'content',
    						'category_id',
    						'user_id'];

   	public function category(){
   		return $this->belongsTo('App\Category');
   	}

   	public function user(){
   		return $this->belongsTo('App\User');
   	}
   	public function images(){
   		return $this->hasMany('App/Image');
   	}
    public function tags(){
        return $this->belongsToMany('App\Tag');
    }

    public function scopeSearch($query, $title){
        return $query->where('title','LIKE',"%$title%");    
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Category;
use App\Tag;
use App\Article;
use App\Image;
use Illuminate\Support\Facades\Redirect;
use Laracasts\Flash\Flash;
use App\Http\Requests\ArticleRequest;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $articles = Article::search($request->title)->orderBy('id','ASC')->paginate(5);
        $articles->each(function($articles){
            $articles->category;
            $articles->user;
        });
        return view('articles.index')->with('articles',$articles);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name','ASC')->lists('name','id');
        $tags = Tag::orderBy('name','ASC')->lists('name','id');

        return view('articles.create')->with('categories',$categories)
                                      ->with('tags',$tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        //Manipulacion de imagenes
        if($request->file('image')){
             $file = $request->file('image');
            $name = 'bloger_' . time() . '.' . $file->getClientOriginalExtension();
            $path = public_path() . '/images/articles/';
            $file->move($path, $name);
        }
        
        $article = new Article($request->all());
        $article->user_id = \Auth::user()->id;
        $article->save();

        $article->tags()->sync($request->tags);

        $image = new Image();
        $image->name = $name;
        $image->article()->associate($article);
        $image->save();

        Flash::success('Se ha creado el artículo' . $article->title . ' de forma exitosa!');
        return redirect()->route('admin.articles.index');

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $articles = Article::find($id);
        $articles->category;
        $categories = Category::orderBy('id','ASC')->lists('name','id');
        $tags = Tag::orderBy('id','ASC')->lists('name','id');

        $my_tags = $articles->tags->lists('id')->ToArray();

        return view('articles.edit')->with('categories',$categories)
                                    ->with('articles',$articles)
                                    ->with('tags', $tags)
                                    ->with('my_tags', $my_tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = Article::find($id);
        $article->fill($request->all());
        $article->save();

        $article->tags()->sync($request->tags);
        Flash::success('El artículo ' . $article->title .' se ha editado de forma exitosa');
        return redirect()->route('admin.articles.index');
    }   

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $article->delete();

        Flash::error('Se ha eliminado el artículo ' .$article->title . ' de forma exitosa');
        return redirect()->route('admin.articles.index');
    }
}

resources/views/articles/create.blade.php
@extends('admin.admin_template')
@section('title','Crear Artículo')

@section('content')
	@if(count($errors) > 0)
		<div class="alert alert-danger" role="alert">
			<ul>
				@foreach($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
	{!! Form::open(['route'=>'admin.articles.store','method'=>'POST','files' => true]) !!}
		<div class="form-group">
			{!! Form::label('title','Título') !!}
			{!! Form::text('title',null,['class' => 'form-control','placeholder' => 'Título de Artículo', 'required']) !!}
		</div>
		<div class="form-grpup">
			{!! Form::label('category_id','Categoria') !!}
			{!! Form::select('category_id', $categories, null,['class' => 'form-control select-category', 'placeholder' => 'Seleccione una Categoria' ,'required']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('content', 'Contenido') !!}
			{!! Form::textarea('content',null, ['class' => 'form-control textarea-content']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('tags', 'Tags')!!}
			{!! Form::select('tags[]',$tags,null,['class' => 'form-control select-tag','multiple','required'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('image','Imagen') !!}
			{!! Form::file('image') !!}
		</div>
		<div class="form-group text-center">
			{!! Form::submit('Agregar Artículo', ['class' => 'btn btn-primary']) !!}
		</div>
	{!! Form::close() !!}
@endsection
@section('js')
	<script>
		$('.select-tag').chosen({
			placeholder_text_multiple: 'Seleccione un máximo de 3 tags',
			max_selected_options : 3,
			no_results_text : 'No se encontró este Tag'
		});
		$('.select-category').chosen({
			no_results_text: 'No se encontró esta Categoria'
		});
		$('.textarea-content').trumbowyg();
	</script>
@endsection

resources/views/articles/edit.blade.php
@extends('admin.admin_template')

@section('title','Editar Artículo - ' . $articles->title)

@section('content')
	@if(count($errors) > 0)
		<div class="alert alert-danger" role="alert">
			<ul>
				@foreach($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
	{!! Form::open(['route'=>['admin.articles.update', $articles->id],'method'=>'PUT']) !!}
		<div class="form-group">
			{!! Form::label('title','Título') !!}
			{!! Form::text('title',$articles->title,['class' => 'form-control','placeholder' => 'Título de Artículo', 'required', 'files' => true]) !!}
		</div>
		<div class="form-grpup">
			{!! Form::label('category_id','Categoria') !!}
			{!! Form::select('category_id', $categories, $articles->category->id,['class' => 'form-control select-category', 'placeholder' => 'Seleccione una Categoria' ,'required']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('content', 'Contenido') !!}
			{!! Form::textarea('content', $articles->content, ['class' => 'form-control textarea-content']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('tags', 'Tags')!!}
			{!! Form::select('tags[]',$tags, $my_tags,['class' => 'form-control select-tag','multiple','required'])!!}
		</div>
		<!-- <div class="form-group">
			{!! Form::label('image', 'Imagen') !!}
			{!! Form::file('image') !!}
		</div> -->
		<div class="form-group text-center">
			{!! Form::submit('Editar Artículo', ['class' => 'btn btn-primary']) !!}
		</div>
	{!! Form::close() !!}
@endsection
@section('js')
	<script>
		$('.select-tag').chosen({
			placeholder_text_multiple: 'Seleccione un máximo de 3 tags',
			max_selected_options : 3,
			no_results_text : 'No se encontró este Tag'
		});
		$('.select-category').chosen({
			no_results_text: 'No se encontró esta Categoria'
		});
		$('.textarea-content').trumbowyg();
	</script>
@endsection

resources/views/articles/index.blade.php
@extends('admin.admin_template')
@section('title', 'Listado de Artículos')

@section('content')
	<a href="{{ route('admin.articles.create') }}" class="btn btn-info">Registrar nuevo Artículo</a>
	<!--Buscador de Artículos -->
		{!! Form::open(['route' => 'admin.articles.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
			<div class="input-group">
				{!! Form::text('title', null,['class' => 'form-control', 'placeholder' => 'Buscar Artículo', 'aria-describedby' => 'search']) !!}
				<span class="input-group-addon" id="search"><span class="glyphicon glyphicon-search"></span></span>
			</div>
		{!! Form::close() !!}
	<!-- Fin buscador -->
	<table class="table table-striped">
		<thead>
			<th>ID</th>
			<th>Título</th>
			<th>Categoria</th>
			<th>User</th>
			<th>Acción</th>
		</thead>
		<tbody>
			@foreach($articles as $article)
			<tr>
				<td>{{ $article->id }}</td>
				<td>{{ $article->title }}</td>
				<td>{{ $article->category->name }}</td>
				<td>{{ $article->user->name }}</td>
				<td>
					<a href="{{ route('admin.articles.edit', $article->id) }}" class="btn btn-warning glyphicon glyphicon-wrench"></a>
					<a href="{{ route('admin.articles.destroy', $article->id) }}" onclick="return confirm('¿Estas seguro de eliminar esta categoria?')" class="btn btn-danger glyphicon glyphicon-remove-circle"></a>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
	<div class="text-center">
		{!! $articles->render() !!}
	</div>


@endsection